# Generated by Django 3.1.1 on 2020-09-19 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Eapp', '0004_auto_20200918_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('product_image', models.ImageField(upload_to='product/%y/%m/%d')),
                ('description', models.TextField()),
                ('product_Cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eapp.categorymodel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
