# Generated by Django 3.1.1 on 2020-09-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0005_productmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='quality',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
