# Generated by Django 3.1.1 on 2020-09-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0006_auto_20200921_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sale_price',
            field=models.CharField(max_length=10),
        ),
    ]
